apiVersion: apps/v1
kind: Deployment
metadata:
  name: ivanjvrhackernews
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ivanjvrhackernews
  template:
    metadata:
      labels:
        app: ivanjvrhackernews
    spec:
      containers:
      - image: okteto.dev/ivanjvrhackernews:latest
        name: ivanjvrhackernews
        envFrom:
        - configMapRef:
            name: ivanjvrhackernews-config
        livenessProbe:
          httpGet:
            path: /ht/
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---

apiVersion: v1
kind: Service
metadata:
  name: ivanjvrhackernews
  annotations:
    dev.okteto.com/auto-ingress: "true"
spec:
  type: ClusterIP  
  ports:
  - name: "ivanjvrhackernews"
    port: 8080
  selector:
    app: ivanjvrhackernews
